### ISSUE TITLE
Move dependencies to devDependencies in package.json

### ISSUE THREAD

**Issue by maoo** [finos/legend-engine-ide-client-vscode#15]
In order to lower attack surface on the NPM released artifact, we encourage moving as many dependencies as possible from `dependencies` to `devDependencies` in `package.json`.

An example is `yo`, which is a command-line utility to build project from templates, and therefore does not seem to be a runtime dependency.

As a direct result, the number of CVEs found in this project will drastically lower.

**Comment by rafaelbey** [comment]
On @gayathrir11 latest PR (https://github.com/finos/legend-engine-ide-client-vscode/pull/34), we have move many of the dependencies into devDependencies, and as suggested on the issue, this have eliminated the CVE findings (last workflow run is now green)
